stages:
  - build
  - test

build:
  stage: build
  image: node
  only:
    changes:
      - package-lock.json
  artifacts:
    paths:
      - build
      - node_modules/  
  script:
    - echo "Building chrome-simple-start"
    - npm ci --verbose
    - npm run build
    - echo "chrome-simple-start build success!"


test:
  stage: test
  needs: ["build"]
  image: node
  script:
    - echo "Starting unit tests"
    - CI=true npm test
    - echo "Unit tests complete!"