image: node
stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Building chrome-simple-start"
    - npm ci --verbose
    - npm run build
    - echo "chrome-simple-start build success!"
    artifacts:
      expire_in: 1 hour
        paths:
          - build
          - node_modules/

test:
  stage: test
  script:
    - echo "Starting unit tests"
    - CI=true npm test
    - echo "Unit tests complete!"