image: node:15-alpine

stages:
  - build
  - test

build:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm
      - node_modules 
  before_script:
    - echo "Building chrome-simple-start"
  script:
    - npm ci --verbose
    - npm run build
  after_script:
    - echo "chrome-simple-start build success!"

test:
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
    paths:
      - .npm
      - node_modules
  before_script:
    - echo "Starting unit tests"
  script:
    - CI=true npm test
  after_script:
    - echo "Unit tests complete!"

variables:
  npm_config_cache: "${CI_PROJECT_DIR}/.npm"
