stages:
  - build
  - test

build:
  stage: build
  image: node
  only:
    changes:
      - package-lock.json
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm
      - node_modules 
  script:
    - echo "Building chrome-simple-start"
    - npm ci --verbose
    - npm run build
    - echo "chrome-simple-start build success!"


test:
  stage: test
  image: node
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
    paths:
      - .npm
      - node_modules
  script:
    - echo "Starting unit tests"
    - CI=true npm test
    - echo "Unit tests complete!"